## Test  Kaerebrum Neural with Keras 
- test if module performs well in accuracy and speed ascompare to current available standards 

In [1]:
import matplotlib.pyplot as plt
import pandas
import tensorflow as tf 
import keras
import sys

import numpy as np
np.set_printoptions(suppress = True)
np.printoptions(threshold=sys.maxsize)

In [2]:
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_valid, y_valid) = mnist.load_data()

In [3]:
X_train = X_train.reshape(-1,28*28)/255
X_valid = X_valid.reshape(-1,28*28)/255

In [4]:
#with np.printoptions(threshold=sys.maxsize):
       #print(X_train[1:5])

## Keras Model

In [17]:
from numpy.random import seed
seed(0)

model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten())  
model.add(tf.keras.layers.Dense(25, activation=tf.nn.relu))
#model.add(tf.keras.layers.Dense(25, activation=tf.nn.sigmoid))
model.add(tf.keras.layers.Dense(10, activation=tf.nn.sigmoid))
#model.add(tf.keras.layers.Dense(10, activation = tf.nn.softmax))

opt = tf.keras.optimizers.Adam(
    learning_rate=0.001,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False
)
model.compile(optimizer = opt, loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])
%time model.fit(X_train, y_train, epochs = 10, batch_size = 32)

Epoch 1/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4031 - accuracy: 0.8885
Epoch 2/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2235 - accuracy: 0.9368
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1916 - accuracy: 0.9460
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1693 - accuracy: 0.9513
Epoch 5/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1530 - accuracy: 0.9554
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1408 - accuracy: 0.9583
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1307 - accuracy: 0.9620
Epoch 8/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1212 - accuracy: 0.9646
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1147 - accuracy: 0.9666
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.107

In [23]:
predictions = model.predict(X_valid)
results = np.argmax(predictions, 1)
accuracy = np.sum(results==y_valid)/y_valid.shape[0]
accuracy

0.9581

## Kaerebrum model 

In [7]:
from Kaerebrum.utils import *
from Kaerebrum import Axon

#### Instructions on methods
from Kaerebrum.Neural import Axon

Call on class function Axon

.1 First argument is a list
   - length of list determined the number of hidden layers
   - each number in the list represents the no of nodes in that layer
   - example [100, 50, 20] will represent 100 nodes in 1st hidden layer and 50 nodes in second and 20 nodes in last hidden layer 
   - input layer and and output layer will nopt be included in this list
   
.2 Second argument is the number of nodes in the output 
 
.3 Third argument is the distribution of the  weights. 
   - 'N' for normal
   - 'U' for uniform
   - '0' initialize weights as 0
   -  None initialize weights as rand - 0.5
   
.4 Fourth argument is the weights initialization method
   - 'He' Kaiming method
   - 'X' Xavier method

In [8]:
from numpy.random import seed
seed(0) 
test = Axon([ 25], 10, 'N', 'He')

.5 the build method lets you input the activation functions and the prefered optimizer
   - activation function is the first argument . Number of activations will be equivilent to the number of hidden layer indicated in the initialization of Axon
   - at this point only relu and sigmiod function 
   - adam and momentum for optimizing function
   
.6 the train method is quite self explainatory for its arguments in the example below. For full batch training set batch = 0 

**Press and hold 'Q' to kill off training process**

In [10]:
test.build([relu, sigmoid], optimizer=adam)   # momentum 
%time pred = test.train(X_train, y_train, epoch = 10, alpha=0.001, batch=32) 

[784, 25, 10]
No of iterations/ n_iters: 10
Learning rate/ alpha: 0.001
Optimizer <function adam at 0x00000190289C5160>
Loss Function: <function logloss at 0x00000190289C5310>
Regularization: None
Shuffle data on each iteration: False
Current accuracy: 0.9167833333333333 for epoch 1:
Cost: 0.17665403785069306
Current accuracy: 0.9330666666666667 for epoch 2:
Cost: 0.13600304279924363
Current accuracy: 0.9410333333333334 for epoch 3:
Cost: 0.11933435225910459
Current accuracy: 0.9470833333333334 for epoch 4:
Cost: 0.10028141951577041
Current accuracy: 0.95135 for epoch 5:
Cost: 0.08676458727587663
Current accuracy: 0.95515 for epoch 6:
Cost: 0.07896442769981007
Current accuracy: 0.95755 for epoch 7:
Cost: 0.07749329913443376
Current accuracy: 0.9601166666666666 for epoch 8:
Cost: 0.08300501741261915
Current accuracy: 0.9614666666666667 for epoch 9:
Cost: 0.08215498077869245
Current accuracy: 0.9633 for epoch 10:
Cost: 0.07814286528389691
Wall time: 36.1 s


In [21]:
pred = test.predict(X_valid)  # predict returns a 2 layer array. 1 st layer be the results and 2nd layer indicate the probablities for each result 

In [22]:
test.accuracy(pred[0], y_valid)

0.9547

#### View params / biases /gradients

In [34]:
# test.params
# test.biases
test.gradients[0]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#### View activated layers

In [28]:
test._activated_layers

[array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[ 0.        ,  0.        , 11.68386083, ...,  0.        ,
          4.6739571 ,  1.45270032],
        [ 0.        ,  0.        ,  5.11970026, ...,  0.        ,
         12.55072313,  1.72222856],
        [ 0.        ,  2.05112385,  0.71540894, ...,  0.        ,
          4.64631603,  3.14154556],
        ...,
        [ 0.        ,  4.15772228,  6.73855122, ...,  0.        ,
          3.02388273,  1.68794535],
        [ 0.        ,  0.        ,  0.        , ...,  0.181006  ,
          6.21584025,  9.86009709],
        [ 0.        ,  0.        ,  1.77154176, ...,  0.        ,
          8.22769435,  0.        ]]),
 array([[0.00000111, 0.        , 0.00001185, ..., 0.99615231, 0.00001759,
         0.00019593],
        [0.00033205, 0.02473